apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: FacService
  namespace: default
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: host
    value: "amqp://admin:Peanut616@192.168.86.181:5672"