apiVersion: apps/v1
kind: Deployment
metadata:
  name: queuetest
  namespace: daprpoc
spec:
  selector:
    matchLabels:
      app: queuetest
  replicas: 1
  template:
    metadata:
      labels:
        app: queuetest
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "queuetest"
        dapr.io/app-port: "80"
        dapr.io/config: "appconfig"
    spec:
      containers:
        - name: queuetest-pod
          image: vsimone67/queuetest:latest
          imagePullPolicy: 'Always'
          ports:
            - name: http
              containerPort: 80
          env:
            - name: 'appdirectory'
              value: '/app/settings/'
          volumeMounts:
            - name: configs
              mountPath: '/app/settings'
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 360
      volumes:
        - name: configs
          projected:
            sources:
              - configMap:
                  name: appsettings-queuetest
              - secret:
                  name: appsettings-secret-queuetest
---
apiVersion: v1
kind: Service
metadata:
  name: queuetest-svc
  namespace: daprpoc
spec:
  ports:
    - name: web
      port: 80
  selector:
    app: queuetest



