apiVersion: apps/v1
kind: Deployment
metadata:
  name: mibprocessor
  namespace: daprpoc
spec:
  selector:
    matchLabels:
      app: mibprocessor
  replicas: 1
  template:
    metadata:
      labels:
        app: mibprocessor
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "mibprocessor"
        dapr.io/app-port: "80"
        dapr.io/config: "appconfig"
    spec:
      containers:
        - name: mibprocessor-pod
          image: vsimone67/mibprocessor:latest
          imagePullPolicy: 'Always'
          ports:
            - name: http
              containerPort: 80
          env:
            - name: 'appdirectory'
              value: '/app/settings/'
          volumeMounts:
            - name: configs
              mountPath: '/app/settings'
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 360
      volumes:
        - name: configs
          projected:
            sources:
              - configMap:
                  name: appsettings-mibprocessor
              - secret:
                  name: appsettings-secret-mibprocessor
---
apiVersion: v1
kind: Service
metadata:
  name: mibprocessor-svc
  namespace: daprpoc
spec:
  ports:
    - name: web
      port: 80
  selector:
    app: mibprocessor
---
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: mibprocessor-route
  namespace: daprpoc
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/mibprocessor/{catchall}`)
      kind: Rule
      services:
        - name: mibprocessor-svc
          port: 80
