apiVersion: apps/v1
kind: Deployment
metadata:
  name: facservice
  namespace: daprpoc
spec:
  selector:
    matchLabels:
      app: facservice
  replicas: 1
  template:
    metadata:
      labels:
        app: facservice
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "facservice"
        dapr.io/app-port: "80"
        dapr.io/config: "appconfig"
    spec:
      containers:
        - name: facservice-pod
          image: vsimone67/facservice:latest
          imagePullPolicy: 'Always'
          ports:
            - name: http
              containerPort: 80
          env:
            - name: 'appdirectory'
              value: '/app/settings/'
          volumeMounts:
            - name: configs
              mountPath: '/app/settings'
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 360
      volumes:
        - name: configs
          projected:
            sources:
              - configMap:
                  name: appsettings-facservice
              - secret:
                  name: appsettings-secret-facservice
---
apiVersion: v1
kind: Service
metadata:
  name: facservice-svcx
  namespace: daprpoc 
spec:  
  ports:
    - name: web
      port: 80     
  selector:
    app: facservice      
---
kind: IngressRoute
apiVersion: traefik.containo.us/v1alpha1
metadata:
  name: facservice-route
  namespace: daprpoc
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`/fac/{catchall}`)
      kind: Rule
      services:
        - name: facservice-svcx
          port: 80


